server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.60.178.135:3306/unsw_comments?useSSL=false&serverTimezone=UTC
    username: root
    password: ss981124
  redis:
    host: 123.60.178.135
    port: 6379
    password: ss981124
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.keyl1me.entity # 别名扫描包
logging:
  level:
    com.keyl1me: debug